server:
  config:
    persistence:
      default:
        driver: "sql"

        sql:
          driver: "postgres"
          host: "rokerage-dev-db-temporal.cluster-cy2utjok3e0t.eu-central-1.rds.amazonaws.com"
          port: 5432
          database: temporal
          user: master
          password: "KkLyDxZmHZssEwCtpE6D3mWpIilQL3qE"
          maxConns: 20
          maxConnLifetime: "1h"

      visibility:
        driver: "sql"

        sql:
          driver: "postgres"
          host: "rokerage-dev-db-temporal.cluster-cy2utjok3e0t.eu-central-1.rds.amazonaws.com"
          port: 5432
          database: temporal_visibility
          user: master
          password: "KkLyDxZmHZssEwCtpE6D3mWpIilQL3qE"
          maxConns: 20
          maxConnLifetime: "1h"

cassandra:
  enabled: false

mysql:
  enabled: false

postgresql:
  enabled: true
  image:
    repo: postgres
    tag: 15.1
    pullPolicy: IfNotPresent

schema:
  setup:
    enabled: true
  update:
    enabled: true
